name: 'Bug Report'
description: 'Report an issue or unexpected behavior in Gland'
labels: ['bug', 'needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ## Before Submitting a Bug Report

        Thank you for taking the time to file a bug report. Please help us address the issue efficiently by:

        - Checking if a similar issue already exists in the issue tracker
        - Making sure your Gland and Node.js versions are up-to-date
        - Providing as much detail as possible about the problem

  - type: checkboxes
    attributes:
      label: 'Prerequisites'
      description: 'Please confirm these steps before submitting your issue'
      options:
        - label: "I have searched for similar issues and couldn't find a solution"
          required: true
        - label: 'I have tried to reproduce this issue with the latest version of Gland'
          required: true
        - label: 'I have checked the documentation and found no answer'
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Current Behavior'
      description: 'A clear description of what actually happens'
      placeholder: 'When I perform X action, the framework does Y instead of Z...'

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Expected Behavior'
      description: 'A clear description of what you expected to happen'
      placeholder: 'I expected the framework to...'

  - type: input
    attributes:
      label: 'Reproduction Link'
      description: 'A link to a minimal repository that reproduces the issue'
      placeholder: 'https://github.com/username/repo'

  - type: textarea
    attributes:
      label: 'Steps to Reproduce'
      description: 'Step-by-step instructions to reproduce the behavior'
      placeholder: |
        1. Initialize Gland with config '...'
        2. Set up event '...'
        3. Trigger event '...'
        4. See error '...'

  - type: textarea
    attributes:
      label: 'Minimal Code Example'
      description: 'If you cannot create a reproduction repository, please provide the smallest code sample that demonstrates the issue'
      value: |
        ```typescript
        // Your code here
        ```

  - type: dropdown
    attributes:
      label: 'Which component of Gland is affected?'
      multiple: true
      options:
        - 'Core'
        - 'Event System'
        - 'Broker'
        - 'Channel'
        - 'Wildcard Events'
        - 'Event Routing'
        - 'Event Connections'
        - 'Middleware'
        - 'Configuration'
        - 'Types'
        - 'Documentation'
        - 'Other'

  - type: input
    validations:
      required: true
    attributes:
      label: 'Gland Version'
      description: 'What version of Gland are you using?'
      placeholder: 'e.g., 1.0.0'

  - type: input
    validations:
      required: true
    attributes:
      label: 'Node.js Version'
      description: 'What version of Node.js are you using?'
      placeholder: 'e.g., 16.13.0'

  - type: input
    attributes:
      label: 'TypeScript Version'
      description: 'If applicable, what version of TypeScript are you using?'
      placeholder: 'e.g., 4.5.4'

  - type: textarea
    attributes:
      label: 'Environment Information'
      description: 'Information about your operating system or any other relevant environment details'
      placeholder: 'OS: Windows 11, Package Manager: npm 8.1.0'

  - type: textarea
    attributes:
      label: 'Error Messages'
      description: 'Include any error messages or stack traces related to the issue'
      value: |
        ```
        Paste error messages here
        ```

  - type: textarea
    attributes:
      label: 'Additional Context'
      description: 'Add any other context about the problem here'
